### ISSUE TITLE
Hold detection algorithm

### ISSUE THREAD

**Issue by javigallostra** [javigallostra/RocoLib#12]
Define the objectives and steps for the Hold Detection Algorithm (HDA).
@juangallostra which type of data do you expect the algorithm to output?

Algorithm steps:

- [x] Image smoothing: Mean Shift Filtering
- [x] Edge detection: Canny
- [ ] Line suppression: ?? research a bit and probably develop an own line segment detection algorithm to remove linear edges
- [ ] Clustering: blob detection, morphological operators to group edges in holds
- [ ] Final filtering: remove clusters that are not holds
- [ ] Data output: parse and deploy results in a convenient way for the webapp

**Comment by juangallostra** [comment]
@javigallostra since I'm currently painting the circles with a constant radius I only need the center coordinates of the holds. I think that a nice format would be a table/matrix with all the image coordinates where a hold is detected such as:
```python
[[0,0,0,0,1,0,0],[1,0,0,0,1,0,0],[0,0,1,0,0,0,1],...]
```

The idea behind is to get some sort of [Hash table](https://es.wikipedia.org/wiki/Tabla_hash). This way it will be easier and faster for me to find the closest hold to the user click. Instead of finding the minimum distance to all the detected holds I will be able to check by coordinate if a hold is present at the click location. If it is not, I will check neighbors until a hold is detected. 

Since having an entry for each pixel might be overkill we can try to tune it and have one entry for a given group of pixels (every 10x10 pixels for example or something like that). 

If it helps, the current radius of the circle I am drawing is 12 pixels.

**Comment by juangallostra** [comment]
@javigallostra we might put this issue on standby for the moment and trust that the user will select actual holds.

**Comment by juangallostra** [comment]
Related project: https://github.com/yarkhinephyo/yolo_bouldering

**Comment by juangallostra** [comment]
[Climbnet's code](https://github.com/cydivision/climbnet) works quite well if the wall images to process are segmentated. This is currently being implemented as a two step process:
1. Run a [modified version](https://github.com/juangallostra/climbnet) of climbnet's code to extrac hold data (a list of polygons that is stored as JSON)
2. Use this JSON hold data to detect if a click falls inside a hold polygon. If it does, draw the hold polygon on the image.

Since detection is not perfect, this might require a post-processing step in between hold detection and polygon extraction, but it is no drama to do so. So, as of now, I think this is the best approach to follow. Closing this issue at the moment.
